import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { buildMessage, validateInput, normalizePhone, metaErrorMessage } from '../functions/ticket-whatsapp/core.ts';
const base = { requestId: '10000000-0000-4000-8000-000000000001', recipient: '+52 614 177 2897', mode: 'contact', consent: true };
assert.equal(normalizePhone('+52 1 6141772897'), '526141772897');
assert.equal(normalizePhone('+1 (202) 555-0184'), '12025550184');
for (const bad of ['6141772897', '+5201', '+52 abc 6141772897', '+52 6141772897 ext 4', '+000000000', '+1234567890123456']) assert.throws(() => normalizePhone(bad));
assert.throws(() => validateInput({ ...base, consent: false }));
assert.throws(() => validateInput({ ...base, requestId: 'bad' }));
assert.throws(() => validateInput({ ...base, mode: 'text', text: 'Hola', recentInbound: false }));
assert.throws(() => validateInput({ ...base, mode: 'text', text: 'a'.repeat(4097), recentInbound: true }));
const contact = validateInput({ ...base, to: '999999999', phoneNumberId: 'untrusted', text: 'ignored' });
assert.equal(contact.text, '');
for (const status of ['PENDING', 'REJECTED', 'PAUSED', undefined]) assert.throws(() => buildMessage(contact, status));
assert.equal(buildMessage(contact, 'APPROVED').payload.to, '526141772897');
assert.equal(buildMessage(contact, 'APPROVED').payload.template.name, 'orion_contacto_soporte_v1');
const ticketId = '10000000-0000-4000-8000-000000000002';
const closure = validateInput({ ...base, mode: 'closure', ticketId });
assert.throws(() => buildMessage(closure, 'APPROVED'));
const ticket = { id: ticketId, estado: 'abierto', numero_caso: 'OR-1', numero_serie_equipo: 'BA400-1' };
assert.throws(() => buildMessage(closure, 'APPROVED', ticket));
const message = buildMessage(closure, 'APPROVED', { ...ticket, estado: 'cerrado' });
assert.equal(message.payload.template.components[0].parameters[0].text, 'OR-1');
assert.equal(message.payload.template.components[0].parameters[1].text, 'BA400-1');
assert.match(metaErrorMessage(131047), /24 horas/);
const { PGlite } = await import(process.env.PGLITE_MODULE || '../_local_archive/whatsapp-tests/node_modules/@electric-sql/pglite/dist/index.js');
const db = new PGlite();
await db.exec(`create role anon; create role authenticated; create role service_role bypassrls; create schema auth; create table auth.users(id uuid primary key); create table public.tickets(id uuid primary key); create function public.is_admin() returns boolean language sql as $$ select current_setting('test.admin',true) = 'yes' $$; grant usage on schema public to authenticated,anon,service_role;`);
await db.exec(await readFile(new URL('../migrations/20260930010000_ticket_whatsapp_messages.sql', import.meta.url), 'utf8'));
await db.exec(`insert into auth.users values ('${base.requestId}'); set role service_role; insert into ticket_whatsapp_messages(id,actor_id,recipient,mode,body,payload_hash) values ('${ticketId}','${base.requestId}','526141772897','text','Prueba','hash'); reset role; set role authenticated; set test.admin='no';`);
assert.equal((await db.query('select * from ticket_whatsapp_messages')).rows.length, 0);
await db.exec("set test.admin='yes'");
assert.equal((await db.query('select * from ticket_whatsapp_messages')).rows.length, 1);
await assert.rejects(db.exec("update ticket_whatsapp_messages set status='accepted'"), /permission denied/);
await assert.rejects(db.exec('delete from ticket_whatsapp_messages'), /permission denied/);
await db.exec('reset role; set role anon');
await assert.rejects(db.exec('select * from ticket_whatsapp_messages'), /permission denied/);
await db.exec('reset role; set role service_role');
await assert.rejects(db.exec(`insert into ticket_whatsapp_messages(id,actor_id,recipient,mode,body,payload_hash) values ('${ticketId}','${base.requestId}','526141772897','text','Otra prueba','hash')`), /duplicate key/);
await db.close();
console.log('PASS: phone validation, no destination overrides, consent, window, template approval, closure data, RLS and duplicate request protection');
