import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const {PGlite}=await import('../_local_archive/whatsapp-tests/node_modules/@electric-sql/pglite/dist/index.js');
const db=new PGlite();
await db.exec(`create role anon; create role authenticated; create role service_role bypassrls; create schema auth; create table auth.users(id uuid primary key); create table profiles(id uuid primary key,nombre_completo text); create table tickets(id uuid primary key,estado text,asunto text,numero_caso text,telefono_cliente_guest text); create table ticket_assignments(ticket_id uuid,assigned_to uuid); create function public.is_admin() returns boolean language sql as $$ select current_setting('test.admin',true)='yes' $$; create function public.ticket_support_area(text) returns text language sql as $$ select 'ingenieria'::text $$; grant usage on schema public to anon,authenticated,service_role;`);
await db.exec(await readFile(new URL('../migrations/20261001010000_ticket_satisfaction.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../migrations/20261001020000_ticket_satisfaction_test_invitations.sql',import.meta.url),'utf8'));
const person='10000000-0000-4000-8000-000000000001',ticket='10000000-0000-4000-8000-000000000002';
await db.exec(`insert into profiles values('${person}','Especialista de prueba'); insert into tickets values('${ticket}','abierto','Servicio','OR-TEST','+526141772897'); insert into ticket_assignments values('${ticket}','${person}'); update tickets set estado='cerrado';`);
let row=(await db.query('select * from ticket_satisfaction')).rows[0];
assert.equal(row.specialist_id,person);assert.equal(row.token.length,64);assert.equal(row.case_number,'OR-TEST');
await db.exec(`update ticket_assignments set assigned_to=null;update tickets set estado='cerrado';`);
assert.equal((await db.query('select * from ticket_satisfaction')).rows.length,1);
assert.equal((await db.query('select specialist_id from ticket_satisfaction')).rows[0].specialist_id,person);
await db.exec('set role anon');await assert.rejects(db.exec('select * from ticket_satisfaction'),/permission denied/);
assert.equal((await db.query("select get_ticket_satisfaction('bad') as info")).rows[0].info,null);
let info=(await db.query('select get_ticket_satisfaction($1) as info',[row.token])).rows[0].info;
assert.deepEqual(Object.keys(info).sort(),['answered','case_number','is_test','specialist_name']);
await assert.rejects(db.query("select submit_ticket_satisfaction($1,6,5,'total',5,'none','')",[row.token]),/Revisa/);
await db.query("select submit_ticket_satisfaction($1,4,3,'partial',null,'followup','Seguimiento de prueba')",[row.token]);
await assert.rejects(db.query("select submit_ticket_satisfaction($1,5,5,'total',5,'none','')",[row.token]),/ya fue respondida/);
await db.exec("reset role;set role authenticated;set test.admin='no'");
assert.equal((await db.query('select * from ticket_satisfaction')).rows.length,0);
await db.exec("set test.admin='yes'");assert.equal((await db.query('select * from ticket_satisfaction')).rows.length,1);
await assert.rejects(db.exec('update ticket_satisfaction set satisfaction=5'),/permission denied/);
await db.exec("reset role;update ticket_satisfaction set expires_at=now()-interval '1 day';set role anon");
assert.equal((await db.query('select get_ticket_satisfaction($1) as info',[row.token])).rows[0].info,null);
await assert.rejects(db.query("select submit_ticket_satisfaction($1,5,5,'total',5,'none','')",[row.token]),/vencido/);
await db.exec("reset role;insert into ticket_satisfaction(is_test,case_number,area) values(true,'PRUEBA','sin_clasificar')");
await assert.rejects(db.exec("insert into ticket_satisfaction(case_number,area) values('INVALID','sin_clasificar')"),/satisfaction_ticket_required/);
assert.equal((await db.query('select count(*)::int as n from ticket_satisfaction where not is_test')).rows[0].n,1);
await db.close();console.log('PASS: automatic creation, assignment snapshot, unique invitation, minimal public projection, RLS, validation, single answer and expiration');
