import {useEffect,useState} from 'react';
import {supabase} from '../../supabaseClient';
import {areaNames,improvements,metrics,specialists,surveyUrl,type Survey} from './model';
import './satisfaction.css';
const show=(v:number|null,suffix='')=>v===null?'—':`${v.toFixed(0)}${suffix}`;
function Orbit({value,label,detail}:{value:number|null;label:string;detail:string}){return <article className="sv-orbit"><svg viewBox="0 0 120 120" aria-hidden="true"><circle cx="60" cy="60" r="49" className="sv-track"/><circle cx="60" cy="60" r="49" className="sv-arc" pathLength="100" strokeDasharray={`${value??0} 100`} transform="rotate(-90 60 60)"/></svg><div><strong>{show(value,'%')}</strong><span>{label}</span></div><small>{detail}</small></article>;}
function Profile({data}:{data:ReturnType<typeof metrics>}){const values=[data.satisfaction===null?null:data.satisfaction*20,data.speed===null?null:data.speed*20,data.resolution,data.clarity===null?null:data.clarity*20];const point=(i:number,v:number)=>[150+Math.sin(i*Math.PI/2)*v,150-Math.cos(i*Math.PI/2)*v];return <svg className="sv-profile" viewBox="0 0 300 300" role="img" aria-label={`Perfil: satisfacción ${show(data.satisfaction,' de 5')}, rapidez ${show(data.speed,' de 5')}, resolución ${show(data.resolution,'%')}, claridad ${show(data.clarity,' de 5')}. Ejes de percepción, no tiempos operativos.`}>{[25,50,75,100].map(r=><polygon key={r} points={[0,1,2,3].map(i=>point(i,r).join(',')).join(' ')} className="sv-gridline"/>)}{[0,1,2,3].map(i=><line key={i} x1="150" y1="150" x2={point(i,100)[0]} y2={point(i,100)[1]} className="sv-gridline"/>)}{values.every(v=>v!==null)&&<polygon className="sv-shape" points={values.map((v,i)=>point(i,v!).join(',')).join(' ')}/>} {values.map((v,i)=>v!==null&&<circle key={i} cx={point(i,v)[0]} cy={point(i,v)[1]} r="5" className="sv-dot"/>)}<text x="150" y="28" textAnchor="middle">Satisfacción</text><text x="252" y="150" textAnchor="middle">Rapidez</text><text x="150" y="280" textAnchor="middle">Resolución</text><text x="46" y="150" textAnchor="middle">Claridad</text>{!data.count&&<text x="150" y="155" textAnchor="middle">Sin respuestas</text>}</svg>;}
function Invitation({row}:{row:Survey}){
 const [notice,setNotice]=useState('');const expired=new Date(row.expires_at)<new Date();
 return <article className="sv-invitation"><div><strong>{row.case_number}</strong><span>{row.specialist_name||'Sin responsable asignado'} · {row.answered_at?'Respondida':expired?'Enlace vencido':'Pendiente de respuesta'}</span></div>{!row.answered_at&&!expired&&<button onClick={()=>void navigator.clipboard.writeText(surveyUrl(row.token)).then(()=>setNotice('Enlace copiado.')).catch(()=>setNotice('No se pudo copiar el enlace.'))}>Copiar enlace</button>}{notice&&<p role="status">{notice}</p>}</article>;
}
export default function SatisfactionDashboard({fixture}:{fixture?:Survey[]}){
 const [rows,setRows]=useState<Survey[]>(fixture||[]),[loading,setLoading]=useState(!fixture),[error,setError]=useState(''),[area,setArea]=useState('ingenieria'),[period,setPeriod]=useState('90'),[chosen,setChosen]=useState(''),[expanded,setExpanded]=useState(false);
 async function load(){setLoading(true);setError('');try{let all:Survey[]=[];for(let offset=0;;offset+=500){const{data,error}=await supabase.from('ticket_satisfaction').select('*').eq('is_test',false).order('created_at',{ascending:false}).order('id').range(offset,offset+499);if(error)throw error;all=all.concat(data as Survey[]);if(data.length<500)break;}setRows(all);}catch{setError('No se pudieron cargar las evaluaciones. Los indicadores no están disponibles.');}finally{setLoading(false);}}
 useEffect(()=>{if(!fixture)void load();},[fixture]);
 const cutoff=period==='all'?0:Date.now()-Number(period)*86400000;
 const filtered=rows.filter(r=>(area==='all'||r.area===area)&&new Date(r.created_at).getTime()>=cutoff);
 const people=specialists(filtered),selected=people.find(p=>p.key===chosen),scope=selected?filtered.filter(r=>`${r.specialist_id}:${r.area}`===selected.key):filtered;
 const m=metrics(error||loading?[]:scope),ranked=people.filter(p=>p.count>=5&&p.area!=='sin_clasificar');
 const recognitions=area==='all'?[]:(['speed','clarity','resolution'] as const).map(key=>{const eligible=ranked.filter(p=>p[key]!==null&&(key!=='clarity'||p.clarityCount>=5));const best=eligible.length?Math.max(...eligible.map(p=>p[key]!)):null;return {key,best,names:eligible.filter(p=>p[key]===best).map(p=>p.name)};});
 const priorities=Object.entries(improvements).map(([key,label])=>({key,label,n:scope.filter(r=>r.answered_at&&r.improvement===key).length})).sort((a,b)=>b.n-a.n);
 return <section className="sv-dashboard"><header className="sv-header"><div><small className="sv-eyebrow">ORION / PULSO DEL SERVICIO</small><h2>La experiencia también mide la excelencia.</h2><p>Voz del cliente · ingeniería y aplicaciones químicas</p></div><button onClick={()=>{setExpanded(v=>!v);}}> {expanded?'Ocultar detalle':'Explorar desempeño'}</button></header>
 <div className="sv-filters"><label>Área<select value={area} onChange={e=>{setArea(e.target.value);setChosen('');}}><option value="all">Todas · sin clasificación conjunta</option>{Object.entries(areaNames).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Cierres del periodo<select value={period} onChange={e=>setPeriod(e.target.value)}><option value="30">Últimos 30 días</option><option value="90">Últimos 90 días</option><option value="all">Desde el inicio</option></select></label><label>Especialista<select value={selected?.key||''} onChange={e=>setChosen(e.target.value)}><option value="">Vista de equipo</option>{people.map(p=><option key={p.key} value={p.key}>{p.name} · {areaNames[p.area]}</option>)}</select></label>{!fixture&&<button onClick={()=>{void load();}} disabled={loading}>Actualizar</button>}</div>
 {error&&<p role="alert" className="sv-error">{error}</p>}{loading&&<p role="status">Cargando evaluaciones…</p>}
 <div className="sv-command"><div className="sv-radar"><small>{selected?.name||'Perfil del equipo'}</small><Profile data={m}/><p>{m.count} respuestas / {m.invited} encuestas creadas</p></div><div className="sv-orbits"><Orbit value={m.csat} label="Satisfacción · CSAT" detail="Calificaciones 4–5 / respuestas"/><Orbit value={m.resolution} label="Resolución total" detail="Solicitudes resueltas / respuestas"/><Orbit value={m.participation} label="Participación" detail="Respuestas / encuestas creadas"/><div className="sv-signal"><small>PERCEPCIÓN DE ATENCIÓN</small><p><strong>{m.speed?.toFixed(1)||'—'}</strong> / 5 · rapidez</p><p><strong>{m.clarity?.toFixed(1)||'—'}</strong> / 5 · claridad <small>({m.clarityCount} respuestas aplicables)</small></p></div></div></div>
 {!m.count&&!loading&&!error&&<p className="sv-empty">Aún no hay evaluaciones para estos filtros. El perfil se construirá con respuestas reales; no se asignan calificaciones por ausencia de datos.</p>}
 {expanded&&!loading&&!error&&<><div className="sv-recognitions">{recognitions.map(r=><article key={r.key}><small>{({speed:'ATENCIÓN OPORTUNA',clarity:'COMUNICACIÓN CLARA',resolution:'SOLUCIÓN EFECTIVA'})[r.key]}</small><strong>{r.names.join(' · ')||'Reconocimiento en formación'}</strong><span>{r.best===null?'Requiere al menos 5 respuestas aplicables':`${r.best.toFixed(1)}${r.key==='resolution'?'%':' / 5'} · mayor resultado del área`}</span></article>)}</div><div className="sv-detail-grid"><div><h3>Referentes del equipo</h3><p>Orden por satisfacción (CSAT). Mínimo 5 respuestas; empate comparte posición. Comparación descriptiva, sin ajuste por complejidad del caso.</p>{area==='all'?<p>Selecciona un área para comparar servicios del mismo tipo.</p>:!ranked.length?<p>En formación · todavía no hay suficiente base para una clasificación.</p>:ranked.map(p=><button className="sv-person" key={p.key} onClick={()=>setChosen(p.key)}><span className="sv-place">{ranked.findIndex(x=>x.csat===p.csat)+1}</span><span><strong>{p.name}</strong><small>{p.count} respuestas · resolución {show(p.resolution,'%')}</small></span><b>{show(p.csat,'%')}<small>CSAT</small></b><span className="sv-person-line" style={{width:`${p.csat||0}%`}}/></button>)}{people.filter(p=>p.count<5).map(p=><p key={p.key}>{p.name} · {p.count}/5 respuestas para entrar en clasificación</p>)}</div><div><h3>Mapa de oportunidades</h3><p>Prioridad elegida por el cliente · {m.count} respuestas</p>{priorities.map(p=><div className="sv-opportunity" key={p.key}><span>{p.label}</span><b>{p.n}</b><div><i style={{width:`${m.count?p.n/m.count*100:0}%`}}/></div></div>)}</div></div>
 <details className="sv-method"><summary>Cómo se calculan los indicadores</summary><p>El periodo agrupa encuestas por fecha de cierre. CSAT: proporción de respuestas con satisfacción 4 o 5. Resolución total: proporción «Totalmente», sin convertirla en resolución en primera visita. Rapidez y claridad son promedios de percepción de 1 a 5; no son el SLA. «No aplica» se excluye de claridad. Participación utiliza todas las encuestas creadas, incluso las aún no enviadas. En el perfil geométrico, los promedios se muestran sobre 100 (promedio × 20); un eje sin datos no se dibuja como cero. No se calcula una puntuación global ni se mezclan áreas en la clasificación. La asignación se conserva al cierre; casos sin responsable no se atribuyen a quien cerró.</p></details>
 <h3>Solicitudes que requieren seguimiento · {m.followup}</h3><p>La encuesta señala casos para revisar; no reabre ni modifica tickets automáticamente.</p>{scope.filter(s=>s.answered_at&&s.resolution!=='total').map(s=><article className="sv-followup" key={s.id}><strong>{s.case_number} · {s.specialist_name||'Sin asignar'}</strong><span>{s.resolution==='partial'?'Parcialmente resuelta':'No resuelta'}</span>{s.comment&&<p>{s.comment}</p>}</article>)}
 <h3>Encuestas del periodo</h3><p>Al cerrar el ticket se programa el envío automático de la encuesta al contacto registrado. El enlace tiene vigencia de 30 días.</p>{scope.slice(0,100).map(row=><Invitation key={row.id} row={row}/>)}{scope.length>100&&<p>Se muestran las 100 encuestas más recientes. Acota el periodo o especialista; los indicadores incluyen todas las del filtro.</p>}
 </>}
 </section>;
}
