import type { DriPlatformKnowledge } from '../types/dri.types';

export const BA400_KNOWLEDGE: DriPlatformKnowledge = {
  model: 'BA400',
  label: 'BA400',
  supportStatus: 'ready',
  supportNote: 'Motor y reglas orientadas primero a BA400.',
  rules: [
    {
      id: 'ba400_optical_photometry',
      platform: 'BA400',
      title: 'Sospecha óptica / fotometría',
      targetSubsystem: 'optical_system',
      summary: 'Patrones dominados por longitud de onda, absorbancia anómala o fotometría anormal.',
      baseSeverity: 'high',
      serviceUtilities: ['photometry', 'baseline_darkness_current', 'metrology', 'historical_reports'],
      confirmatoryActions: [
        'Ejecutar Photometry y revisar línea base / darkness current.',
        'Comparar pruebas 340 nm contra filtros distintos.',
        'Revisar cubetas, rotor de reacción y blanco de cubeta.',
      ],
      correctiveActions: [
        'Limpiar o revisar cubetas y sistema óptico antes de tocar refacciones.',
        'Corregir filtros / alineación solo después de confirmar desviación reproducible.',
      ],
      candidateParts: ['Filtro óptico', 'Conjunto fotométrico', 'Rotor de reacción'],
      checklist: [
        {
          id: 'opt-1',
          title: 'Correr Photometry',
          utilityId: 'photometry',
          utilityLabel: 'Photometry',
          serviceScriptIds: ['14', '88'],
          expectedResult: 'Lecturas dentro de tolerancia y sin drift.',
          interpretation: 'Si falla solo una longitud de onda, priorizar filtro/óptica localizada.',
          onPass: 'Reducir peso de hipótesis óptica global.',
          onFail: 'Escalar óptica/fotometría y revisar cubetas, baseline y metrología.',
        },
        {
          id: 'opt-2',
          title: 'Revisar baseline y darkness current',
          utilityId: 'baseline_darkness_current',
          utilityLabel: 'Baseline and darkness current',
          serviceScriptIds: ['14', '88'],
          expectedResult: 'Línea base estable, sin ruido ni offset excesivo.',
          interpretation: 'Ruido o offset sugieren problema óptico o suciedad.',
          onPass: 'Revisar entonces método o reactivo.',
          onFail: 'Priorizar limpieza, cubetas y ruta óptica.',
        },
      ],
    },
    {
      id: 'ba400_r2_dispensing',
      platform: 'BA400',
      title: 'Sospecha R2 / mezcla / dispensación secundaria',
      targetSubsystem: 'reagent_arm_r2',
      summary: 'Fallas dominantes en técnicas birreactivas con contraste positivo contra monoreactivas.',
      baseSeverity: 'high',
      serviceUtilities: ['motors_valves_pumps', 'positioning', 'stress_mode', 'conditioning'],
      confirmatoryActions: [
        'Comparar birreactivas contra monoreactivas equivalentes.',
        'Verificar brazo R2, timing y mezcla.',
        'Revisar pumps / valves y conditioning.',
      ],
      correctiveActions: [
        'Purgar y condicionar antes de desmontar.',
        'Revisar obstrucción, burbujas y válvulas previas a cambio de piezas.',
      ],
      candidateParts: ['Brazo R2', 'Bomba de reactivo', 'Válvula de dispensación', 'Agitador'],
      checklist: [
        {
          id: 'r2-1',
          title: 'Verificar Motors, valves and pumps',
          utilityId: 'motors_valves_pumps',
          utilityLabel: 'Motors, valves and pumps',
          serviceScriptIds: ['1031', '1032', '1033', '1055', '1056', '1065', '1066', '1304', '1305'],
          expectedResult: 'Secuencias y consumos normales.',
          interpretation: 'Anomalías aumentan sospecha de dispensación secundaria.',
          onPass: 'Mover foco a software/método o reactivo.',
          onFail: 'Revisar línea R2, válvula, bomba y cebado.',
        },
        {
          id: 'r2-2',
          title: 'Revisar positioning y stress mode',
          utilityId: 'positioning',
          utilityLabel: 'Positioning',
          serviceScriptIds: ['96', '98', '103', '104'],
          expectedResult: 'Brazo y agitador llegan a posición consistente.',
          interpretation: 'Desfase o inestabilidad apoyan mezcla / timing.',
          onPass: 'Bajar peso mecánico.',
          onFail: 'Revisar positioning, agitadores y brazo R2.',
        },
      ],
    },
    {
      id: 'ba400_temperature',
      platform: 'BA400',
      title: 'Sospecha de termostatización / estabilidad de reactivo',
      targetSubsystem: 'reaction_rotor',
      summary: 'Dominan pruebas enzimáticas/cinéticas o existe temperatura anormal reportada.',
      baseSeverity: 'high',
      serviceUtilities: ['thermostatting', 'analyzer_information', 'historical_reports'],
      confirmatoryActions: [
        'Ejecutar Thermostatting.',
        'Comparar enzimáticas sensibles vs endpoint estables.',
        'Revisar refrigeración y estabilidad abordo.',
      ],
      correctiveActions: [
        'Confirmar temperatura del rotor y refrigerador antes de culpar al reactivo.',
        'Validar reactivo fresco y estabilidad abordo.',
      ],
      candidateParts: ['Sensor térmico', 'Rotor de reacción', 'Módulo de refrigeración'],
      checklist: [
        {
          id: 'temp-1',
          title: 'Correr Thermostatting',
          utilityId: 'thermostatting',
          utilityLabel: 'Thermostatting',
          serviceScriptIds: ['105', '2019'],
          expectedResult: 'Temperaturas estables y dentro de rango.',
          interpretation: 'Fuera de rango o inestable respalda hipótesis térmica.',
          onPass: 'Mover foco a reactivo o configuración.',
          onFail: 'Escalar termostatización y revisar sensores/refrigeración.',
        },
      ],
    },
    {
      id: 'ba400_fluidics_pipetting',
      platform: 'BA400',
      title: 'Sospecha de pipeteo / fluídica / dilución',
      targetSubsystem: 'fluidics',
      summary: 'Patrones no proporcionales en dilución, repetibilidad pobre o bajo volumen sensible.',
      baseSeverity: 'high',
      serviceUtilities: ['motors_valves_pumps', 'level_detection', 'conditioning', 'dilution_review'],
      confirmatoryActions: [
        'Ejecutar linealidad 1:2, 1:4 y 1:5.',
        'Verificar factor de dilución aplicado.',
        'Revisar burbujas, volumen muerto, válvulas y detección de nivel.',
      ],
      correctiveActions: [
        'Condicionar y purgar antes de desmontar.',
        'Confirmar si LIS muestra valor corregido o crudo.',
      ],
      candidateParts: ['Bomba de muestra', 'Válvula', 'Detección de nivel', 'Línea fluídica'],
      checklist: [
        {
          id: 'flu-1',
          title: 'Verificar proportionalidad de dilución',
          utilityId: 'dilution_review',
          utilityLabel: 'Dilution review',
          serviceScriptIds: ['1031', '1032', '1033', '1055', '1056', '1065', '1066', '1304', '1305'],
          expectedResult: 'Relaciones 1:2, 1:4, 1:5 proporcionales.',
          interpretation: 'Exacta mitad sugiere software/factor; no proporcional sugiere pipeteo o mezcla.',
          onPass: 'Bajar hipótesis mecánica.',
          onFail: 'Subir hipótesis fluídica/pipeteo.',
        },
        {
          id: 'flu-2',
          title: 'Correr level detection y conditioning',
          utilityId: 'level_detection',
          utilityLabel: 'Level detection',
          serviceScriptIds: ['3001', '3002', '3003', '3004', '1410'],
          expectedResult: 'Toma de muestra y diluyente consistente.',
          interpretation: 'Falla apoya burbuja, obstrucción o error de nivel.',
          onPass: 'Revisar software o método.',
          onFail: 'Escalar fluidics / pipetting.',
        },
      ],
    },
    {
      id: 'ba400_wash_carryover',
      platform: 'BA400',
      title: 'Sospecha de lavado / contaminación / carryover',
      targetSubsystem: 'wash_station',
      summary: 'Blanco fallido, rechazo óptico local o comportamiento intermitente compatible con arrastre.',
      baseSeverity: 'medium',
      serviceUtilities: ['washing_station', 'conditioning', 'historical_reports'],
      confirmatoryActions: [
        'Revisar estación de lavado y solución de lavado.',
        'Revisar residuos, agua destilada y carryover.',
      ],
      correctiveActions: [
        'Corregir insumos de lavado y contaminación antes de cambiar piezas.',
      ],
      candidateParts: ['Estación de lavado', 'Línea de lavado', 'Cubetas'],
      checklist: [
        {
          id: 'wash-1',
          title: 'Inspeccionar washing station',
          utilityId: 'washing_station',
          utilityLabel: 'Washing station',
          serviceScriptIds: ['57', '58', '59', '1101', '1103', '1105', '1201', '1209', '1412', '1415', '1416', '1418'],
          expectedResult: 'Lavado y secado consistentes, sin residuos.',
          interpretation: 'Residuo, burbuja o arrastre elevan carryover.',
          onPass: 'Bajar peso de contaminación.',
          onFail: 'Priorizar lavado, cubetas e insumos.',
        },
      ],
    },
    {
      id: 'ba400_control_preanalytical',
      platform: 'BA400',
      title: 'Sospecha de control / calibrador / error preanalítico',
      targetSubsystem: 'preanalytical',
      summary: 'Muchas fallas sin patrón técnico común fuerte o curvas normales con QC fuera de rango.',
      baseSeverity: 'medium',
      serviceUtilities: ['historical_reports', 'software_configuration'],
      confirmatoryActions: [
        'Revisar lote, preparación, caducidad y almacenamiento.',
        'Validar calibración activa y técnica configurada.',
      ],
      correctiveActions: [
        'No mover piezas hasta descartar control/calibrador/reactivo.',
      ],
      candidateParts: [],
      checklist: [
        {
          id: 'ctrl-1',
          title: 'Revisar preparación y lote',
          utilityId: 'historical_reports',
          utilityLabel: 'Historical reports',
          expectedResult: 'Sin cambio abrupto por lote o preparación.',
          interpretation: 'Si el patrón no es técnico, revisar preanalítico primero.',
          onPass: 'Mover peso a patrón técnico.',
          onFail: 'Escalar control/calibrador/reactivo.',
        },
      ],
    },
    {
      id: 'ba400_procedure_limitation_interference',
      platform: 'BA400',
      title: 'Sospecha de interferencia analítica / limitación del procedimiento',
      targetSubsystem: 'preanalytical',
      summary: 'El propio IFU del reactivo describe interferencias o limitaciones que pueden explicar el sesgo sin culpar al hardware.',
      baseSeverity: 'medium',
      serviceUtilities: ['historical_reports', 'software_configuration'],
      confirmatoryActions: [
        'Comparar el resultado contra los umbrales IFU de bilirrubina, hemólisis y lipemia.',
        'Confirmar si la muestra o control exceden las limitaciones del procedimiento.',
        'Repetir con dilución, nueva muestra o método alternativo cuando aplique.',
      ],
      correctiveActions: [
        'No mover piezas si el comportamiento coincide con una interferencia documentada.',
        'Documentar la limitación del procedimiento y confirmar con la muestra/analito interferente.',
      ],
      candidateParts: [],
      checklist: [
        {
          id: 'limit-1',
          title: 'Revisar limitaciones del procedimiento',
          utilityId: 'historical_reports',
          utilityLabel: 'Historical reports / IFU',
          expectedResult: 'Las concentraciones interferentes no exceden los umbrales del IFU.',
          interpretation: 'Si el interferente excede el umbral, primero explicar el sesgo por limitación analítica.',
          onPass: 'Bajar peso de interferencia y volver a revisar patrón técnico.',
          onFail: 'Priorizar interferencia / procedimiento antes de hipótesis mecánicas.',
        },
      ],
    },
    {
      id: 'ba400_metrology_range',
      platform: 'BA400',
      title: 'Sospecha de fuera de linealidad / rango metrológico',
      targetSubsystem: 'operational',
      summary: 'El resultado capturado cae fuera del rango metrológico del reactivo o exige dilución/corrección antes de interpretar el diagnóstico.',
      baseSeverity: 'medium',
      serviceUtilities: ['software_configuration', 'historical_reports', 'dilution_review'],
      confirmatoryActions: [
        'Comparar el valor obtenido con el límite de linealidad del IFU.',
        'Verificar dilución manual o automática y su factor de corrección.',
        'Repetir dentro del rango lineal antes de asumir un problema mecánico.',
      ],
      correctiveActions: [
        'Diluir y repetir según IFU antes de escalar a hardware.',
        'Confirmar unidad reportada y configuración de la técnica.',
      ],
      candidateParts: [],
      checklist: [
        {
          id: 'met-1',
          title: 'Verificar linealidad y unidad del resultado',
          utilityId: 'dilution_review',
          utilityLabel: 'Dilution review',
          expectedResult: 'El valor queda dentro del rango lineal del IFU o se corrige con dilución.',
          interpretation: 'Fuera de linealidad, la prioridad es corregir medición/dilución antes de culpar al equipo.',
          onPass: 'Reevaluar hipótesis mecánicas con el resultado corregido.',
          onFail: 'Escalar a revisión de configuración, dilución y manejo de muestra.',
        },
      ],
    },
    {
      id: 'ba400_software_operational',
      platform: 'BA400',
      title: 'Sospecha operativa / software / configuración',
      targetSubsystem: 'software',
      summary: 'El comportamiento apunta a factor de dilución, técnica configurada o calibración activa errónea.',
      baseSeverity: 'medium',
      serviceUtilities: ['software_configuration', 'analyzer_information', 'historical_reports'],
      confirmatoryActions: [
        'Revisar técnica, factor de dilución y unidades.',
        'Confirmar si LIS muestra valor corregido o crudo.',
      ],
      correctiveActions: [
        'Corregir configuración antes de tocar hardware.',
      ],
      candidateParts: [],
      checklist: [
        {
          id: 'soft-1',
          title: 'Revisar configuración analítica',
          utilityId: 'software_configuration',
          utilityLabel: 'Configuración de técnica',
          expectedResult: 'Factor, dilución y calibración activos correctos.',
          interpretation: 'Si el resultado se reduce exactamente a la mitad, priorizar software.',
          onPass: 'Bajar peso de error operativo.',
          onFail: 'Corregir configuración / LIS.',
        },
      ],
    },
  ],
};
