import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright-core';

const url = process.env.BA400_PREVIEW_URL || 'http://127.0.0.1:5173/orion/dri-preview';
const out = new URL('../../outputs/ba400-verification/', import.meta.url);
await fs.mkdir(out, { recursive: true });
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const checks = [];
const pageErrors = [];
const writes = [];
const failedResponses = [];
const page = await browser.newPage({ viewport: { width: 1600, height: 1100 }, deviceScaleFactor: 1 });
page.on('pageerror', e => pageErrors.push(e.message));
page.on('request', request => { if (['POST', 'PUT', 'PATCH', 'DELETE'].includes(request.method()) && /supabase|rest\/v1/.test(request.url())) writes.push(request.url()); });
page.on('response', r => { if (r.status() >= 400 && !r.url().includes('favicon')) failedResponses.push([r.status(), r.url()]); });
let modelRequests = 0;
page.on('request', r => { if (new URL(r.url()).pathname.endsWith('BA400_web.glb')) modelRequests++; });
const workspace = page.locator('.ba400-workspace');
const inspector = page.locator('.ba400-inspector');
const ready = async (p = page) => {
  await p.getByTestId('ba400-canvas').waitFor({ timeout: 60000 });
  await p.waitForFunction(() => ['ready', 'error'].includes(document.querySelector('[data-testid="ba400-canvas"]')?.getAttribute('data-state')), null, { timeout: 60000 });
  assert.equal(await p.getByTestId('ba400-canvas').getAttribute('data-state'), 'ready', await p.locator('.ba400-stage').innerText());
};
const choose = async (title) => { await page.locator('.ba400-finding-list').getByRole('button', { name: new RegExp(title) }).click(); await page.waitForTimeout(850); };
const screenshot = async (name, target = page) => { await target.screenshot({ path: fileURLToPath(new URL(name + '.png', out)) }); };
const stageScreenshot = async name => { await page.getByTestId('ba400-stage').screenshot({ path: fileURLToPath(new URL(name + '.png', out)) }); };
try {
  await page.goto(url);
  await ready();
  assert.equal(await page.locator('.ba400-finding').count(), 6);
  assert.match(await workspace.innerText(), /PRUEBA LOCAL/);
  assert.equal(await page.locator('.ba400-part-tag').count(), 0);
  await page.waitForTimeout(850);
  await screenshot('01-demo-overview');
  checks.push('DEMO BA400 opens offline seeded real-engine case, six findings, assembled model');
  // Actual raycast selection, not a catalog click.
  const canvas = await page.locator('.ba400-canvas canvas').boundingBox();
  await page.mouse.click(canvas.x + canvas.width * .5, canvas.y + canvas.height * .55);
  await page.locator('.ba400-inspector-title').waitFor();
  assert.match(await inspector.innerText(), /Identificador/);
  checks.push('Clicking the actual model selects a catalog part without creating findings');
  assert.equal(await page.locator('.ba400-finding').count(), 6);
  await choose('óptica / fotometría');
  assert.match(await inspector.innerText(), /Banco óptico sin filtros/);
  assert.match(await inspector.innerText(), /AC16614/);
  assert.match(await inspector.innerText(), /Sospecha · sin confirmar/);
  assert.equal(await page.getByRole('button', { name: 'Mostrar tapas', exact: true }).getAttribute('aria-pressed'), 'true');
  await screenshot('02-dri-to-optical-bank');
  checks.push('Single finding → AC16614 → banco_opt, camera focus, covers hidden, evidence retained');
  await page.getByRole('button', { name: 'Aislar componente', exact: true }).click();
  await page.waitForTimeout(850);
  assert.match(await page.locator('.ba400-stage-footer').innerText(), /COMPONENTE AISLADO/);
  await screenshot('03-isolated-bank');
  await page.getByRole('button', { name: 'Ver ubicación en el equipo', exact: true }).click();
  assert.match(await page.locator('.ba400-stage-footer').innerText(), /CONTEXTO VISIBLE/);
  checks.push('Isolate and return to location preserve diagnostic selection and context');
  await choose('lavado / contaminación');
  assert.match(await inspector.innerText(), /1 de 2/);
  assert.match(await inspector.innerText(), /Cabezal de lavado/);
  await page.getByRole('button', { name: 'Componente siguiente', exact: true }).click();
  assert.match(await inspector.innerText(), /2 de 2/);
  assert.match(await inspector.innerText(), /Rotor desechable/);
  await page.getByRole('button', { name: 'Componente anterior', exact: true }).click();
  assert.match(await inspector.innerText(), /1 de 2/);
  checks.push('Multi-component finding cycles both pieces with explicit selection indicators');
  await page.getByLabel('Despiece visual').press('Home');
  for (let step = 0; step < 55; step++) await page.getByLabel('Despiece visual').press('ArrowRight');
  await page.waitForTimeout(850);
  assert.equal(await page.locator('.ba400-explosion output').innerText(), '55 %');
  await screenshot('04-explosion');
  await choose('R2 / mezcla');
  assert.equal(await page.locator('.ba400-explosion output').innerText(), '0 %');
  assert.match(await inspector.innerText(), /Brazo R2/);
  checks.push('Gradual explosion and switching diagnosis restore assembled positions');
  await page.getByRole('button', { name: 'Mostrar tapas', exact: true }).click();
  assert.match(await page.locator('.ba400-stage-footer').innerText(), /EQUIPO COMPLETO/);
  await page.getByRole('button', { name: 'Ocultar tapas', exact: true }).click();
  checks.push('Show/hide covers toggles the real viewer state');
  await page.getByText('Explorar catálogo · 318 piezas', { exact: true }).click();
  await page.getByPlaceholder('Nombre, código o part_id').fill('filtro_340');
  await page.locator('.ba400-catalog-results').getByRole('button', { name: /Filtro 340 nm/ }).click();
  await page.waitForTimeout(850);
  assert.match(await inspector.innerText(), /AC16606/);
  assert.match(await inspector.innerText(), /Sin hallazgos DRI asociados/);
  await stageScreenshot('05-internal-filter');
  checks.push('Internal filter visible behind hidden optical covers; no invented diagnosis on a catalog selection');
  await page.getByPlaceholder('Nombre, código o part_id').fill('led_340');
  await page.locator('.ba400-catalog-results').getByRole('button', { name: /LED 340 nm/ }).click();
  await page.getByRole('button', { name: 'Aislar componente', exact: true }).click();
  await page.waitForTimeout(850);
  assert.match(await inspector.innerText(), /led_340/);
  await stageScreenshot('06-nested-led-isolated');
  checks.push('Nested led_340 can be selected, isolated and inspected independently of pcb_foto');
  await page.getByPlaceholder('Nombre, código o part_id').fill('ise_rot_01');
  await page.locator('.ba400-catalog-results').getByRole('button', { name: /Rotor de tres rodillos ISE 1/ }).click();
  await page.getByRole('button', { name: 'Aislar componente', exact: true }).click();
  await page.waitForTimeout(850);
  assert.match(await inspector.innerText(), /ise_rot_01/);
  assert.match(await inspector.innerText(), /Sin hallazgos DRI asociados/);
  await stageScreenshot('09-new-ise-rotor');
  checks.push('Updated GLB exposes new ISE rotor through catalog, isolation and selection without inventing findings');
  await choose('control / calibrador');
  assert.match(await inspector.innerText(), /Sin componente 3D asociado/);
  assert.equal(await page.locator('.ba400-part-tag').count(), 0);
  assert.equal(await page.getByRole('button', { name: 'Aislar componente', exact: true }).isDisabled(), true);
  assert.equal(await page.locator('.ba400-finding').count(), 6);
  checks.push('Unmapped diagnostic preserved, no stale highlight or isolation');
  assert.equal(modelRequests, 1, 'Changing findings must not request the GLB again');
  checks.push('All finding and part changes use one model download');
  await choose('óptica / fotometría');
  await page.getByRole('button', { name: 'Restablecer equipo', exact: true }).click();
  await page.waitForTimeout(850);
  assert.match(await inspector.innerText(), /Equipo restablecido/);
  assert.equal(await page.locator('.ba400-explosion output').innerText(), '0 %');
  assert.equal(await page.locator('.ba400-part-tag').count(), 0);
  await choose('óptica / fotometría');
  assert.match(await inspector.innerText(), /Banco óptico sin filtros/);
  checks.push('Reset clears inspection state; selecting the same finding locates it again');
  await page.getByLabel('Equipo del visor DRI').selectOption('BA200');
  assert.match(await workspace.innerText(), /Este modelo 3D solo corresponde al BA400/);
  assert.equal(await page.locator('.ba400-canvas canvas').count(), 0);
  assert.equal(await page.locator('.ba400-finding').count(), 0);
  const previousRequests = modelRequests;
  await page.getByRole('button', { name: 'Demo BA400', exact: true }).first().click();
  await ready();
  assert.equal(modelRequests, previousRequests, 'Remount must reuse cached bytes');
  checks.push('Equipment change removes stale BA400 findings and graphics; DEMO reload reuses cached bytes');
  await page.getByRole('button', { name: 'Generar diagnóstico diferencial', exact: true }).click();
  await ready();
  assert.match(await page.locator('.dri-shell').innerText(), /Prueba local: el diagnóstico no se guarda en producción/);
  assert.equal(writes.length, 0);
  await page.getByRole('button', { name: 'Reiniciar', exact: true }).click();
  assert.equal(await page.locator('.ba400-finding').count(), 0);
  assert.equal(await page.locator('.ba400-canvas canvas').count(), 0);
  await page.getByRole('button', { name: 'Demo BA400', exact: true }).first().click();
  await ready();
  assert.equal(modelRequests, 1);
  checks.push('Generating a demo diagnosis cannot persist it; resetting capture clears findings and reopening still uses cached bytes');
  // Responsive verification of the same functional page.
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByTestId('ba400-stage').scrollIntoViewIfNeeded();
  await page.waitForTimeout(500);
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), 'Mobile horizontal overflow');
  await screenshot('07-mobile');
  checks.push('390px layout retains usable model, controls, catalog and findings without page overflow');
  assert.equal(pageErrors.length, 0, pageErrors.join('\n'));
  assert.equal(writes.length, 0, 'No production diagnostic writes are permitted in DEMO');
  assert.equal(failedResponses.length, 0, JSON.stringify(failedResponses));
  // New browser context has no module cache: simulate a real recoverable HTTP failure.
  const errorPage = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  let attempts = 0;
  await errorPage.route('**/BA400_web.glb*', async route => {
    attempts++;
    if (attempts === 1) await route.fulfill({ status: 503, body: 'Fixture de prueba: modelo temporalmente no disponible' });
    else await route.continue();
  });
  await errorPage.goto(url);
  await errorPage.getByRole('button', { name: 'Reintentar carga', exact: true }).waitFor({ timeout: 30000 });
  assert.equal(await errorPage.locator('.ba400-finding').count(), 6);
  assert.match(await errorPage.locator('.ba400-stage').innerText(), /HTTP 503/);
  await screenshot('08-recoverable-error', errorPage);
  await errorPage.getByRole('button', { name: 'Reintentar carga', exact: true }).click();
  await ready(errorPage);
  assert.equal(attempts, 2);
  checks.push('HTTP 503 shows recoverable error, preserves six findings and succeeds on retry');
  await errorPage.close();
  const result = { checks: checks.length, passed: checks, modelRequests, pageErrors, productionWrites: writes, failedResponses };
  await fs.writeFile(new URL('browser-tests.json', out), JSON.stringify(result, null, 2));
  console.log(JSON.stringify(result, null, 2));
} catch (error) {
  await screenshot('failure');
  console.error(JSON.stringify({ checks, pageErrors, failedResponses, body: (await workspace.innerText()).slice(0, 8000) }));
  throw error;
} finally { await browser.close(); }
