import assert from 'node:assert/strict';
import { chromium } from 'playwright-core';
const browser=await chromium.launch({channel:'chrome',headless:true});
try {
 const page=await browser.newPage({viewport:{width:1550,height:1050}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.clock.install({time:new Date('2026-10-02T18:00:00Z')});
 await page.goto('http://127.0.0.1:5200/orion/tests/fixtures/live-planning.html');
 await page.getByRole('heading',{name:'Ingenieros y químicos'}).waitFor();
 await page.getByLabel('Área del equipo').selectOption('Química / Aplicaciones');
 await page.getByText('Hospital Central',{exact:true}).waitFor();
 await page.getByText('Laboratorio del Norte',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Pantalla completa',exact:true}).click();
 assert.equal(await page.locator('.engineer-wall--screen').count(),1);
 assert.equal(await page.locator('table').count(),0);
 await page.screenshot({path:'/tmp/engineer-chemist-wall.png',fullPage:true});
 await page.getByRole('button',{name:'Salir de pantalla completa'}).click();
 await page.getByLabel('Área del equipo').selectOption('all');
 await page.getByRole('button',{name:'Siguiente',exact:true}).click();
 await page.getByText('Panel 2 / 2',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Editar planeación'}).click();
 await page.getByRole('heading',{name:'Equipo en vivo'}).waitFor();
 assert.equal(await page.getByRole('button',{name:/Erick/}).count(),0);
 await page.getByLabel('Localidad Atoyac',{exact:true}).fill('ERROR');
 await page.getByLabel('Localidad Atoyac',{exact:true}).press('Enter');
 await page.getByRole('alert').filter({hasText:'Error de prueba'}).waitFor();
 await page.getByLabel('Localidad Atoyac',{exact:true}).fill('Nueva localidad');
 await page.getByLabel('Localidad Atoyac',{exact:true}).press('Enter');
 await page.getByLabel('Localidad Nueva localidad',{exact:true}).waitFor();
 await page.getByRole('button',{name:'+ Agregar fila',exact:true}).click();
 await page.locator('form').getByLabel('Localidad',{exact:true}).fill('Nueva visita');
 await page.locator('form').getByLabel('Fecha',{exact:true}).fill('2026-10-15');
 await page.getByRole('button',{name:'Guardar fila',exact:true}).click();
 await page.getByLabel('Localidad Nueva visita',{exact:true}).waitFor();
 await page.getByRole('button',{name:/Hector Cortes/}).click();
 await page.getByText('Sin actividades para este mes o filtro.',{exact:false}).waitFor();
 await page.getByRole('button',{name:'Ver todo el equipo'}).click();
 await page.screenshot({path:'/tmp/live-planning-board.png',fullPage:true});
 assert.deepEqual(errors,[]);
 console.log('PASS: fullscreen, chemistry filter, pagination, current and overdue activities, roster, inactive engineer, save failure/retry, add row, engineer filter, render.');
} finally {await browser.close();}
