import assert from 'node:assert/strict';
import { ticketControlFacts, summarizeControl, hoursBetween, formatDuration } from '../src/components/ticketControlModel.ts';
const start = '2026-09-01T00:00:00Z';
const end = hours => new Date(Date.parse(start) + hours * 3600000).toISOString();
const ticket = { id:'test', creado_en:start, estado:'cerrado' };
const closure = (hours, reason='solucionado') => ({ ticket_id:'test', kind:'cierre', occurred_at:end(hours), closure_reason:reason, actor_id:'engineer', profiles:{nombre_completo:'Ana'} });
const facts = (events, state='cerrado', now=72) => ticketControlFacts({...ticket,estado:state},events,Date.parse(end(now)));
assert.equal(facts([closure(48)]).sla,'dentro');
assert.equal(facts([closure(48.01)]).sla,'vencido');
assert.equal(facts([], 'abierto', 40).sla,'por_vencer');
assert.equal(facts([], 'abierto', 39).sla,'dentro');
assert.equal(facts([]).sla,'sin_dato');
assert.equal(facts([closure(12,null)]).solved,false);
assert.equal(facts([closure(12,'visita_programada')]).solved,false);
const justified = facts([closure(72),{kind:'justificacion'}]);
assert.equal(justified.sla,'justificado');
const reviewed = facts([closure(72),{kind:'revision_cierre'}]);
assert.equal(reviewed.sla,'vencido');
assert.equal(summarizeControl([reviewed]).reviewPending,0);
const summary = summarizeControl([facts([closure(24)]), facts([closure(72)]), justified, facts([closure(1,'sin_respuesta')]), facts([])]);
assert.equal(summary.compliance,50);
assert.equal(summary.eligible,2);
assert.equal(summary.solved,3);
assert.equal(summary.missing,1);
assert.equal(summary.justified,1);
assert.equal(hoursBetween(start,'invalid'),null);
assert.equal(hoursBetween(end(1),start),null);
assert.equal(formatDuration(49.5),'2 d 1 h 30 min');
assert.equal(formatDuration(null),'Sin dato');
assert.equal(facts([closure(2)]).owner,'Ana');
console.log('PASS: SLA boundaries, missing history, administrative closures, review vs approval, adjusted denominator, attribution and durations');
