import assert from 'node:assert/strict';
import { createServer } from 'vite';
import { chromium } from 'playwright-core';
const server = await createServer({ server: { host: '127.0.0.1', port: 5198, strictPort: true } });
await server.listen();
const browser = await chromium.launch({ channel: 'chrome', headless: true, args: ['--disable-features=LocalNetworkAccessChecks'] });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  page.setDefaultTimeout(12000);
  const errors = [];
  page.on('pageerror', error => { if(errors.length < 5) errors.push(error.stack); });
  page.on('dialog', dialog => dialog.accept());
  await page.route('**/supabaseClient.ts', route => route.fulfill({ contentType: 'text/javascript', body: 'export const getValidatedUser=async()=>null;export const supabase={};' }));
  await page.route('**/trackingStatusApi.ts', route => route.fulfill({ contentType: 'text/javascript', body: 'export const supportsLivePortalLookup=()=>false;export const usesCloudTrackingAgentLookup=()=>false;export const lookupTrackingInCarrierPortal=async()=>({});' }));
  await page.route('**/trackingPersistenceApi.ts', route => route.fulfill({ contentType: 'text/javascript', body: `
    import {coerceTrackingEntry} from '/orion/src/components/orionTracking.ts';
    const get=()=>JSON.parse(localStorage.getItem('test-cloud'));
    const put=value=>localStorage.setItem('test-cloud',JSON.stringify(value));
    if(!get())put({dismissed:[],rows:['en_transito','en_reparto','entregado','incidencia','capturado'].map((status,i)=>coerceTrackingEntry({id:'fixture-'+i,carrier:'dhl',trackingNumber:String(1000000000+i),status,fulfillmentState:status==='entregado'?'entregado':'pendiente',recipient:'Cliente de prueba '+i,destination:'Ciudad de México',estimatedDelivery:i===0?'2020-01-01':'2099-01-01',timeline:[],source:'dhl_push'}))});
    export const loadCloudTrackingEntries=async()=>({userId:'fixture-user',entries:get().rows,dismissedNumbers:get().dismissed,queuedEntryIds:[]});
    export const loadTrackingAgentHealth=async()=>null;
    export const requestCloudTrackingRefresh=async()=>'';
    export const replaceCloudTrackingEntries=async(_,entries)=>{const db=get();for(const entry of entries){if(db.dismissed.includes(entry.trackingNumber))continue;const index=db.rows.findIndex(row=>row.trackingNumber===entry.trackingNumber);if(index<0)db.rows.push(entry);else db.rows[index]=entry;}put(db);};
    export const dismissCloudTrackings=async numbers=>{const db=get();db.dismissed.push(...numbers);db.rows=db.rows.filter(row=>!numbers.includes(row.trackingNumber));put(db);};
    export const restoreCloudTrackings=async numbers=>{const db=get();db.dismissed=db.dismissed.filter(number=>!numbers.includes(number));put(db);};
  ` }));
  await page.route('**/board-check', route => route.fulfill({ contentType:'text/html',body:`<html><body style="margin:0"><div id="root"></div><script type="module">import R from '/orion/@react-refresh';R.injectIntoGlobalHook(window);window.$RefreshReg$=()=>{};window.$RefreshSig$=()=>type=>type;window.__vite_plugin_react_preamble_installed__=true;await import('/orion/tests/fixtures/tracking-board.tsx');</script></body></html>` }));
  const open = async () => {
    await page.getByRole('button',{name:'Tablero en vivo',exact:true}).click();
    await page.locator('.tracking-live-board--open').waitFor();
    if(await page.evaluate(()=>!!document.fullscreenElement))await page.evaluate(()=>document.exitFullscreen());
    await page.waitForFunction(()=>getComputedStyle(document.querySelector('.tracking-live-board')).opacity==='1');
  };
  await page.goto('http://127.0.0.1:5198/orion/board-check');
  await open();
  const rows=page.locator('.tracking-live-board__row');
  await rows.first().waitFor();assert.equal(await rows.count(),5);
  const filter=page.getByLabel('Filtrar envíos por estado');
  await filter.selectOption('risk');assert.equal(await rows.count(),2);
  assert.equal(await page.locator('.tracking-alert-pulse').count(),2);
  assert.equal(await page.locator('.tracking-alert-pulse').first().evaluate(el=>getComputedStyle(el).animationIterationCount),'3');
  await filter.selectOption('entregado');assert.equal(await rows.count(),1);
  await filter.selectOption('late');assert.equal(await rows.count(),1);
  await page.getByRole('button',{name:'Eliminar guía 1000000000',exact:true}).click();
  await page.getByText('No hay envíos con este filtro.').waitFor();
  await page.reload();await open();assert.equal(await rows.count(),4);
  await page.screenshot({path:'/tmp/orion-board-desktop.png'});
  await page.setViewportSize({width:390,height:844});
  assert(await page.locator('.tracking-live-board__shell').evaluate(el=>el.scrollWidth<=el.clientWidth+1));
  await page.screenshot({path:'/tmp/orion-board-mobile.png'});
  await page.locator('.tracking-live-board').getByRole('button',{name:'Cerrar',exact:true}).click();
  await page.getByRole('button',{name:'+ Agregar guías',exact:true}).click();
  await page.getByLabel('Guía(s) o texto a procesar').fill('1000000000');
  await page.locator('.tracking-panel--composer select').first().selectOption('dhl');
  await page.getByRole('button',{name:'Agregar tracking',exact:true}).click();
  await page.waitForFunction(()=>JSON.parse(localStorage.getItem('test-cloud')).rows.length===5);
  await open();assert.equal(await rows.count(),5);
  assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('test-cloud')).dismissed),[]);
  assert.deepEqual(errors,[]);
  console.log('PASS: compact board, status filters, bounded pulse, persistent dismissal after reload, mobile width.');
} finally {await browser.close();await server.close();}
