begin;

insert into public.reagents (
  id,
  name,
  calibration_mode,
  read_mode,
  primary_wavelength_nm,
  reference_wavelength_nm,
  reported_method,
  reagent_type,
  operational_note,
  preliminary_risk,
  source_status,
  confidence,
  source_type,
  source_reference
)
values
  ('ADA', 'ADA', 'Lineal', 'Mono', 340, null, 'Cinética monoreactiva', 'Monoreactiva', 'Enzimático/cinético; revisar estabilidad por IFU', 'Medio', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · ADA'),
  ('ACP', 'Acid Phosphatase ACP', 'Lineal', 'Mono', 405, null, 'Cinética monoreactiva', 'Monoreactiva', 'Archivo indica nota de uso/validación; requiere revisión técnica', 'Alto', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · ACP'),
  ('ALT_GPT', 'ALT/GPT', 'Lineal', 'Mono', 340, null, 'BA: cinética bireactiva; A15/A25: cinética monoreactiva', 'Variable por plataforma', 'Reacción decreciente; blanco inicial crítico según IFU', 'Alto', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · ALT_GPT'),
  ('ALB', 'Albumin', 'Lineal', 'Bicro', 635, 670, 'Punto final monoreactivo', 'Monoreactiva', 'Grupo óptico 635/670', 'Bajo', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · ALB'),
  ('MALB_U', 'Microalbumin urine', 'Lineal', 'Mono', 535, null, 'Tiempo fijo; configuración cambia por lote', 'Variable por lote', 'Cambio lote/configuración; requiere control de versión', 'Alto', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · MALB_U'),
  ('ALP_AMP', 'ALP-AMP', 'Lineal', 'Mono', 405, null, 'Cinética monoreactiva', 'Monoreactiva', 'Enzimático/cinético', 'Medio', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · ALP_AMP'),
  ('ALP_DEA', 'ALP-DEA', 'Lineal', 'Mono', 405, null, 'Cinética bireactiva', 'Bireactiva', 'Comparte filtro con ALP-AMP, diferente esquema reactivo', 'Medio', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · ALP_DEA'),
  ('AMY', 'Alpha-amylase direct', 'Lineal', 'Mono', 405, null, 'Cinética monoreactiva', 'Monoreactiva', 'Enzimático/cinético', 'Medio', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · AMY'),
  ('AGLU', 'Alpha-glucosidase', 'Lineal', 'Mono', 505, null, 'Cinética bireactiva', 'Bireactiva', 'Enzimático/cinético', 'Medio', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · AGLU'),
  ('NH3', 'Ammonia', 'Lineal', 'Mono', 340, null, 'Diferencial bireactiva', 'Bireactiva', 'Grupo 340 nm', 'Medio', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · NH3'),
  ('ACE', 'ACE', 'Lineal', 'Mono', 340, null, 'Cinética monoreactiva', 'Monoreactiva', 'Enzimático/cinético', 'Medio', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · ACE'),
  ('AST_GOT', 'AST/GOT', 'Lineal', 'Mono', 340, null, 'BA: cinética bireactiva; A15/A25: cinética monoreactiva', 'Variable por plataforma', 'Reacción decreciente; blanco inicial crítico según IFU', 'Alto', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · AST_GOT'),
  ('BIL_D', 'Bilirubin Direct DPD', 'Lineal', 'Bicro', 535, 670, 'Diferencial bireactiva', 'Bireactiva', 'Relacionada con Bilirrubina Total', 'Medio', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · BIL_D'),
  ('BIL_T', 'Bilirubin Total DPD', 'Lineal', 'Bicro', 535, 670, 'Diferencial bireactiva', 'Bireactiva', 'Relacionada con Bilirrubina Directa', 'Medio', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · BIL_T'),
  ('CRP', 'CRP', 'Lineal', 'Variable', 535, 670, 'BA: diferencial bireactiva; A15/A25: punto final monoreactivo', 'Variable por plataforma', 'Cambia comportamiento según plataforma', 'Alto', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · CRP'),
  ('CA_ARS', 'Calcium Arsenazo', 'Lineal', 'Mono', 635, null, 'Punto final monoreactivo', 'Monoreactiva', 'Sensible a calidad del agua', 'Alto', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · CA_ARS'),
  ('CA_CPC', 'Calcium Cresolphthalein', 'Lineal', 'Mono', 560, null, 'Diferencial bireactiva', 'Bireactiva', 'Sensible a calidad del agua', 'Alto', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · CA_CPC'),
  ('CER', 'Ceruloplasmin', 'No lineal', 'Bicro', 340, 670, 'Diferencial bireactiva', 'Bireactiva', 'Calibración no lineal/multipunto', 'Alto', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · CER'),
  ('CHOL', 'Cholesterol', 'Lineal', 'Bicro', 505, 670, 'Punto final monoreactivo', 'Monoreactiva', 'Grupo 505/670 endpoint', 'Bajo', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · CHOL'),
  ('CK', 'Creatine Kinase CK', 'Lineal', 'Mono', 340, null, 'Cinética bireactiva', 'Bireactiva', 'Enzimático/cinético; grupo 340 nm', 'Alto', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · CK'),
  ('CREA_ENZ', 'Creatinine Enzymatic', 'Lineal', 'Mono', 535, null, 'Diferencial bireactiva', 'Bireactiva', 'Nodo 535 diferencial', 'Medio', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · CREA_ENZ'),
  ('CREA_JAFFE', 'Creatinine Jaffe', 'Lineal', 'Mono', 535, null, 'Diferencial bireactiva', 'Bireactiva', 'Nodo 535 diferencial', 'Medio', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · CREA_JAFFE'),
  ('FRUCT', 'Fructosamine', 'Lineal', 'Mono', 535, null, 'Tiempo fijo monoreactivo', 'Monoreactiva', 'Nota de validación; dependencia con albúmina sérica', 'Alto', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · FRUCT'),
  ('GGT', 'GGT', 'Lineal', 'Mono', 405, null, 'Cinética bireactiva', 'Bireactiva', 'Enzimático/cinético', 'Medio', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · GGT'),
  ('GLU', 'Glucose', 'Lineal', 'Bicro', 505, 670, 'Punto final monoreactivo', 'Monoreactiva', 'Grupo 505/670 endpoint', 'Bajo', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · GLU'),
  ('G6PDH', 'G6PDH', 'Lineal', 'Mono', 340, null, 'Cinética bireactiva', 'Bireactiva', 'Enzimático/cinético; grupo 340 nm', 'Alto', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · G6PDH'),
  ('GLU_HK', 'Glucose-Hexokinase', 'Lineal', 'Mono', 340, null, 'Diferencial bireactiva', 'Bireactiva', 'Grupo 340 nm', 'Medio', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · GLU_HK'),
  ('HAPTO', 'Haptoglobin', 'No lineal', 'Bicro', 340, 670, 'Diferencial bireactiva', 'Bireactiva', 'Calibración no lineal/multipunto', 'Alto', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · HAPTO'),
  ('HCY', 'Homocysteine', 'No lineal', 'Mono', 340, null, 'Punto final bireactivo', 'Bireactiva', 'Calibración no lineal/multipunto', 'Alto', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · HCY'),
  ('MG', 'Magnesium', 'Lineal', 'Mono', 505, null, 'Punto final bireactivo', 'Bireactiva', 'Sensible a calidad del agua', 'Alto', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · MG'),
  ('OX', 'Oxalate', 'Lineal', 'Mono', 600, null, 'Diferencial bireactiva', 'Bireactiva', 'Muestra crítica: pH/HCl/estabilidad', 'Alto', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · OX'),
  ('PHOS', 'Phosphorous', 'Lineal', 'Mono', 340, null, 'Diferencial bireactiva', 'Bireactiva', 'Sensible a calidad del agua', 'Alto', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · PHOS'),
  ('PROT_U', 'Protein Urine', 'Lineal', 'Bicro', 600, 670, 'Punto final monoreactivo', 'Monoreactiva', 'Grupo 600/670', 'Medio', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · PROT_U'),
  ('TG', 'Triglycerides', 'Lineal', 'Bicro', 505, 670, 'Punto final monoreactivo', 'Monoreactiva', 'Grupo 505/670 endpoint', 'Bajo', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · TG'),
  ('TBA', 'Total Bile Acids', 'Lineal', 'Mono', 405, null, 'Tiempo fijo bireactivo', 'Bireactiva', 'Lecturas después de R2', 'Medio', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · TBA'),
  ('UREA_COLOR', 'Urea BUN-Color', 'Lineal', 'Mono', 600, null, 'Punto final bireactivo', 'Bireactiva', 'Preparación working reagent; revisar validación', 'Alto', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · UREA_COLOR'),
  ('UREA_UV', 'Urea BUN-UV', 'Lineal', 'Mono', 340, null, 'A15/A25: tiempo fijo monoreactivo; BA: tiempo fijo bireactivo', 'Variable por plataforma', 'Cambia según plataforma', 'Alto', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · UREA_UV'),
  ('URIC', 'Uric Acid', 'Lineal', 'Bicro', 505, 670, 'Punto final monoreactivo', 'Monoreactiva', 'Grupo 505/670 endpoint', 'Bajo', 'Pendiente IFU/programación', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 01_Reactivos_Base · URIC')
on conflict (id) do update
set
  name = excluded.name,
  calibration_mode = excluded.calibration_mode,
  read_mode = excluded.read_mode,
  primary_wavelength_nm = excluded.primary_wavelength_nm,
  reference_wavelength_nm = excluded.reference_wavelength_nm,
  reported_method = excluded.reported_method,
  reagent_type = excluded.reagent_type,
  operational_note = excluded.operational_note,
  preliminary_risk = excluded.preliminary_risk,
  source_status = excluded.source_status,
  confidence = excluded.confidence,
  source_type = excluded.source_type,
  source_reference = excluded.source_reference,
  updated_at = timezone('utc', now());

insert into public.reagent_factors (
  id,
  factor_type,
  label,
  value_text,
  value_numeric,
  unit,
  description,
  priority,
  source_status,
  confidence,
  source_type,
  source_reference
)
values
  ('WL_340', 'wavelength', 'Filtro/longitud 340 nm', '340', 340, 'nm', 'Conexión por longitud de onda principal o referencia.', 'Alta', 'Pendiente revisión', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 02_Factores · WL_340'),
  ('WL_405', 'wavelength', 'Filtro/longitud 405 nm', '405', 405, 'nm', 'Conexión por longitud de onda principal o referencia.', 'Alta', 'Pendiente revisión', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 02_Factores · WL_405'),
  ('WL_505', 'wavelength', 'Filtro/longitud 505 nm', '505', 505, 'nm', 'Conexión por longitud de onda principal o referencia.', 'Alta', 'Pendiente revisión', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 02_Factores · WL_505'),
  ('WL_535', 'wavelength', 'Filtro/longitud 535 nm', '535', 535, 'nm', 'Conexión por longitud de onda principal o referencia.', 'Alta', 'Pendiente revisión', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 02_Factores · WL_535'),
  ('WL_560', 'wavelength', 'Filtro/longitud 560 nm', '560', 560, 'nm', 'Conexión por longitud de onda principal o referencia.', 'Alta', 'Pendiente revisión', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 02_Factores · WL_560'),
  ('WL_600', 'wavelength', 'Filtro/longitud 600 nm', '600', 600, 'nm', 'Conexión por longitud de onda principal o referencia.', 'Alta', 'Pendiente revisión', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 02_Factores · WL_600'),
  ('WL_635', 'wavelength', 'Filtro/longitud 635 nm', '635', 635, 'nm', 'Conexión por longitud de onda principal o referencia.', 'Alta', 'Pendiente revisión', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 02_Factores · WL_635'),
  ('WL_670', 'wavelength', 'Filtro/longitud 670 nm', '670', 670, 'nm', 'Conexión por longitud de onda principal o referencia.', 'Alta', 'Pendiente revisión', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 02_Factores · WL_670'),
  ('METHOD_CINETICA_MONOREACTIVA', 'method', 'Cinética monoreactiva', null, null, null, 'Método de cálculo/lectura para agrupar patrones de falla.', 'Alta', 'Pendiente revisión', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 02_Factores · METHOD_CINETICA_MONOREACTIVA'),
  ('METHOD_CINETICA_BIREACTIVA', 'method', 'Cinética bireactiva', null, null, null, 'Método de cálculo/lectura para agrupar patrones de falla.', 'Alta', 'Pendiente revisión', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 02_Factores · METHOD_CINETICA_BIREACTIVA'),
  ('METHOD_PUNTO_FINAL_MONOREACTIVO', 'method', 'Punto final monoreactivo', null, null, null, 'Método de cálculo/lectura para agrupar patrones de falla.', 'Alta', 'Pendiente revisión', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 02_Factores · METHOD_PUNTO_FINAL_MONOREACTIVO'),
  ('METHOD_PUNTO_FINAL_BIREACTIVO', 'method', 'Punto final bireactivo', null, null, null, 'Método de cálculo/lectura para agrupar patrones de falla.', 'Alta', 'Pendiente revisión', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 02_Factores · METHOD_PUNTO_FINAL_BIREACTIVO'),
  ('METHOD_DIFERENCIAL_BIREACTIVA', 'method', 'Diferencial bireactiva', null, null, null, 'Método de cálculo/lectura para agrupar patrones de falla.', 'Alta', 'Pendiente revisión', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 02_Factores · METHOD_DIFERENCIAL_BIREACTIVA'),
  ('METHOD_TIEMPO_FIJO_MONOREACTIVO', 'method', 'Tiempo fijo monoreactivo', null, null, null, 'Método de cálculo/lectura para agrupar patrones de falla.', 'Alta', 'Pendiente revisión', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 02_Factores · METHOD_TIEMPO_FIJO_MONOREACTIVO'),
  ('METHOD_TIEMPO_FIJO_BIREACTIVO', 'method', 'Tiempo fijo bireactivo', null, null, null, 'Método de cálculo/lectura para agrupar patrones de falla.', 'Alta', 'Pendiente revisión', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 02_Factores · METHOD_TIEMPO_FIJO_BIREACTIVO'),
  ('RXTYPE_MONOREACTIVA', 'reaction_type', 'Monoreactiva', null, null, null, 'Tipo de esquema reactivo.', 'Alta', 'Pendiente revisión', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 02_Factores · RXTYPE_MONOREACTIVA'),
  ('RXTYPE_BIREACTIVA', 'reaction_type', 'Bireactiva', null, null, null, 'Tipo de esquema reactivo.', 'Alta', 'Pendiente revisión', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 02_Factores · RXTYPE_BIREACTIVA'),
  ('RXTYPE_VARIABLE_POR_PLATAFORMA', 'reaction_type', 'Variable por plataforma', null, null, null, 'Tipo de esquema reactivo.', 'Alta', 'Pendiente revisión', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 02_Factores · RXTYPE_VARIABLE_POR_PLATAFORMA'),
  ('RXTYPE_VARIABLE_POR_LOTE', 'reaction_type', 'Variable por lote', null, null, null, 'Tipo de esquema reactivo.', 'Alta', 'Pendiente revisión', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 02_Factores · RXTYPE_VARIABLE_POR_LOTE'),
  ('RISK_SENSIBLE_A_CALIDAD', 'risk', 'Sensible a calidad del agua', null, null, null, 'Riesgo operativo a confirmar contra IFU/validación interna.', 'Media/Alta', 'Pendiente revisión', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 02_Factores · RISK_SENSIBLE_A_CALIDAD'),
  ('RISK_CALIBRACION_NO_LIN', 'risk', 'Calibración no lineal/multipunto', null, null, null, 'Riesgo operativo a confirmar contra IFU/validación interna.', 'Media/Alta', 'Pendiente revisión', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 02_Factores · RISK_CALIBRACIÓN_NO_LIN'),
  ('RISK_REACCION_DECRECIEN', 'risk', 'Reacción decreciente/blanco crítico', null, null, null, 'Riesgo operativo a confirmar contra IFU/validación interna.', 'Media/Alta', 'Pendiente revisión', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 02_Factores · RISK_REACCIÓN_DECRECIEN'),
  ('RISK_MUESTRA_PREANALITI', 'risk', 'Muestra preanalítica crítica', null, null, null, 'Riesgo operativo a confirmar contra IFU/validación interna.', 'Media/Alta', 'Pendiente revisión', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 02_Factores · RISK_MUESTRA_PREANALÍTI'),
  ('RISK_ENZIMATICO_CINETIC', 'risk', 'Enzimático/cinético', null, null, null, 'Riesgo operativo a confirmar contra IFU/validación interna.', 'Media/Alta', 'Pendiente revisión', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 02_Factores · RISK_ENZIMÁTICO_CINÉTIC'),
  ('RISK_CAMBIO_POR_LOTE_PL', 'risk', 'Cambio por lote/plataforma', null, null, null, 'Riesgo operativo a confirmar contra IFU/validación interna.', 'Media/Alta', 'Pendiente revisión', 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 02_Factores · RISK_CAMBIO_POR_LOTE_PL')
on conflict (id) do update
set
  factor_type = excluded.factor_type,
  label = excluded.label,
  value_text = excluded.value_text,
  value_numeric = excluded.value_numeric,
  unit = excluded.unit,
  description = excluded.description,
  priority = excluded.priority,
  source_status = excluded.source_status,
  confidence = excluded.confidence,
  source_type = excluded.source_type,
  source_reference = excluded.source_reference,
  updated_at = timezone('utc', now());

insert into public.reagent_factor_links (
  reagent_id,
  factor_id,
  relation_type,
  weight,
  confidence,
  source_type,
  source_reference,
  source_label,
  note
)
values
  ('ADA', 'WL_340', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 2', 'Aspects/pages + revisión pendiente', 'ADA usa filtro principal 340 nm'),
  ('ADA', 'METHOD_CINETICA_MONOREACTIVA', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 3', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Cinética monoreactiva'),
  ('ADA', 'RXTYPE_MONOREACTIVA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 4', 'Aspects/pages + revisión pendiente', 'Monoreactiva'),
  ('ADA', 'RISK_ENZIMATICO_CINETIC', 'riesgo_operativo', 0.75, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 5', 'Archivo usuario/pendiente IFU', 'Enzimático/cinético; revisar estabilidad por IFU'),
  ('ACP', 'WL_405', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 6', 'Aspects/pages + revisión pendiente', 'Acid Phosphatase ACP usa filtro principal 405 nm'),
  ('ACP', 'METHOD_CINETICA_MONOREACTIVA', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 7', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Cinética monoreactiva'),
  ('ACP', 'RXTYPE_MONOREACTIVA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 8', 'Aspects/pages + revisión pendiente', 'Monoreactiva'),
  ('ALT_GPT', 'WL_340', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 9', 'Aspects/pages + revisión pendiente', 'ALT/GPT usa filtro principal 340 nm'),
  ('ALT_GPT', 'METHOD_CINETICA_MONOREACTIVA', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 10', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Cinética monoreactiva'),
  ('ALT_GPT', 'METHOD_CINETICA_BIREACTIVA', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 11', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Cinética bireactiva'),
  ('ALT_GPT', 'RXTYPE_VARIABLE_POR_PLATAFORMA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 12', 'Aspects/pages + revisión pendiente', 'Variable por plataforma'),
  ('ALT_GPT', 'RISK_REACCION_DECRECIEN', 'riesgo_operativo', 0.9, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 13', 'Archivo usuario/pendiente IFU', 'Reacción decreciente; blanco inicial crítico según IFU'),
  ('ALB', 'WL_635', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 14', 'Aspects/pages + revisión pendiente', 'Albumin usa filtro principal 635 nm'),
  ('ALB', 'WL_670', 'usa_filtro_referencia', 0.75, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 15', 'Aspects/pages + revisión pendiente', 'Albumin usa filtro referencia 670 nm'),
  ('ALB', 'METHOD_PUNTO_FINAL_MONOREACTIVO', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 16', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Punto final monoreactivo'),
  ('ALB', 'RXTYPE_MONOREACTIVA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 17', 'Aspects/pages + revisión pendiente', 'Monoreactiva'),
  ('MALB_U', 'WL_535', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 18', 'Aspects/pages + revisión pendiente', 'Microalbumin urine usa filtro principal 535 nm'),
  ('MALB_U', 'RXTYPE_VARIABLE_POR_LOTE', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 19', 'Aspects/pages + revisión pendiente', 'Variable por lote'),
  ('MALB_U', 'RISK_CAMBIO_POR_LOTE_PL', 'riesgo_operativo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 20', 'Archivo usuario/pendiente IFU', 'Cambio lote/configuración; requiere control de versión'),
  ('ALP_AMP', 'WL_405', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 21', 'Aspects/pages + revisión pendiente', 'ALP-AMP usa filtro principal 405 nm'),
  ('ALP_AMP', 'METHOD_CINETICA_MONOREACTIVA', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 22', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Cinética monoreactiva'),
  ('ALP_AMP', 'RXTYPE_MONOREACTIVA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 23', 'Aspects/pages + revisión pendiente', 'Monoreactiva'),
  ('ALP_AMP', 'RISK_ENZIMATICO_CINETIC', 'riesgo_operativo', 0.75, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 24', 'Archivo usuario/pendiente IFU', 'Enzimático/cinético'),
  ('ALP_DEA', 'WL_405', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 25', 'Aspects/pages + revisión pendiente', 'ALP-DEA usa filtro principal 405 nm'),
  ('ALP_DEA', 'METHOD_CINETICA_BIREACTIVA', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 26', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Cinética bireactiva'),
  ('ALP_DEA', 'RXTYPE_BIREACTIVA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 27', 'Aspects/pages + revisión pendiente', 'Bireactiva'),
  ('AMY', 'WL_405', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 28', 'Aspects/pages + revisión pendiente', 'Alpha-amylase direct usa filtro principal 405 nm'),
  ('AMY', 'METHOD_CINETICA_MONOREACTIVA', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 29', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Cinética monoreactiva'),
  ('AMY', 'RXTYPE_MONOREACTIVA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 30', 'Aspects/pages + revisión pendiente', 'Monoreactiva'),
  ('AMY', 'RISK_ENZIMATICO_CINETIC', 'riesgo_operativo', 0.75, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 31', 'Archivo usuario/pendiente IFU', 'Enzimático/cinético'),
  ('AGLU', 'WL_505', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 32', 'Aspects/pages + revisión pendiente', 'Alpha-glucosidase usa filtro principal 505 nm'),
  ('AGLU', 'METHOD_CINETICA_BIREACTIVA', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 33', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Cinética bireactiva'),
  ('AGLU', 'RXTYPE_BIREACTIVA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 34', 'Aspects/pages + revisión pendiente', 'Bireactiva'),
  ('AGLU', 'RISK_ENZIMATICO_CINETIC', 'riesgo_operativo', 0.75, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 35', 'Archivo usuario/pendiente IFU', 'Enzimático/cinético'),
  ('NH3', 'WL_340', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 36', 'Aspects/pages + revisión pendiente', 'Ammonia usa filtro principal 340 nm'),
  ('NH3', 'METHOD_DIFERENCIAL_BIREACTIVA', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 37', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Diferencial bireactiva'),
  ('NH3', 'RXTYPE_BIREACTIVA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 38', 'Aspects/pages + revisión pendiente', 'Bireactiva'),
  ('ACE', 'WL_340', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 39', 'Aspects/pages + revisión pendiente', 'ACE usa filtro principal 340 nm'),
  ('ACE', 'METHOD_CINETICA_MONOREACTIVA', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 40', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Cinética monoreactiva'),
  ('ACE', 'RXTYPE_MONOREACTIVA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 41', 'Aspects/pages + revisión pendiente', 'Monoreactiva'),
  ('ACE', 'RISK_ENZIMATICO_CINETIC', 'riesgo_operativo', 0.75, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 42', 'Archivo usuario/pendiente IFU', 'Enzimático/cinético'),
  ('AST_GOT', 'WL_340', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 43', 'Aspects/pages + revisión pendiente', 'AST/GOT usa filtro principal 340 nm'),
  ('AST_GOT', 'METHOD_CINETICA_MONOREACTIVA', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 44', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Cinética monoreactiva'),
  ('AST_GOT', 'METHOD_CINETICA_BIREACTIVA', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 45', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Cinética bireactiva'),
  ('AST_GOT', 'RXTYPE_VARIABLE_POR_PLATAFORMA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 46', 'Aspects/pages + revisión pendiente', 'Variable por plataforma'),
  ('AST_GOT', 'RISK_REACCION_DECRECIEN', 'riesgo_operativo', 0.9, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 47', 'Archivo usuario/pendiente IFU', 'Reacción decreciente; blanco inicial crítico según IFU'),
  ('BIL_D', 'WL_535', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 48', 'Aspects/pages + revisión pendiente', 'Bilirubin Direct DPD usa filtro principal 535 nm'),
  ('BIL_D', 'WL_670', 'usa_filtro_referencia', 0.75, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 49', 'Aspects/pages + revisión pendiente', 'Bilirubin Direct DPD usa filtro referencia 670 nm'),
  ('BIL_D', 'METHOD_DIFERENCIAL_BIREACTIVA', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 50', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Diferencial bireactiva'),
  ('BIL_D', 'RXTYPE_BIREACTIVA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 51', 'Aspects/pages + revisión pendiente', 'Bireactiva'),
  ('BIL_T', 'WL_535', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 52', 'Aspects/pages + revisión pendiente', 'Bilirubin Total DPD usa filtro principal 535 nm'),
  ('BIL_T', 'WL_670', 'usa_filtro_referencia', 0.75, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 53', 'Aspects/pages + revisión pendiente', 'Bilirubin Total DPD usa filtro referencia 670 nm'),
  ('BIL_T', 'METHOD_DIFERENCIAL_BIREACTIVA', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 54', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Diferencial bireactiva'),
  ('BIL_T', 'RXTYPE_BIREACTIVA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 55', 'Aspects/pages + revisión pendiente', 'Bireactiva'),
  ('CRP', 'WL_535', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 56', 'Aspects/pages + revisión pendiente', 'CRP usa filtro principal 535 nm'),
  ('CRP', 'WL_670', 'usa_filtro_referencia', 0.75, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 57', 'Aspects/pages + revisión pendiente', 'CRP usa filtro referencia 670 nm'),
  ('CRP', 'METHOD_PUNTO_FINAL_MONOREACTIVO', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 58', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Punto final monoreactivo'),
  ('CRP', 'METHOD_DIFERENCIAL_BIREACTIVA', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 59', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Diferencial bireactiva'),
  ('CRP', 'RXTYPE_VARIABLE_POR_PLATAFORMA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 60', 'Aspects/pages + revisión pendiente', 'Variable por plataforma'),
  ('CRP', 'RISK_CAMBIO_POR_LOTE_PL', 'riesgo_operativo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 61', 'Archivo usuario/pendiente IFU', 'Cambia comportamiento según plataforma'),
  ('CA_ARS', 'WL_635', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 62', 'Aspects/pages + revisión pendiente', 'Calcium Arsenazo usa filtro principal 635 nm'),
  ('CA_ARS', 'METHOD_PUNTO_FINAL_MONOREACTIVO', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 63', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Punto final monoreactivo'),
  ('CA_ARS', 'RXTYPE_MONOREACTIVA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 64', 'Aspects/pages + revisión pendiente', 'Monoreactiva'),
  ('CA_ARS', 'RISK_SENSIBLE_A_CALIDAD', 'riesgo_operativo', 0.9, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 65', 'Archivo usuario/pendiente IFU', 'Sensible a calidad del agua'),
  ('CA_CPC', 'WL_560', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 66', 'Aspects/pages + revisión pendiente', 'Calcium Cresolphthalein usa filtro principal 560 nm'),
  ('CA_CPC', 'METHOD_DIFERENCIAL_BIREACTIVA', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 67', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Diferencial bireactiva'),
  ('CA_CPC', 'RXTYPE_BIREACTIVA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 68', 'Aspects/pages + revisión pendiente', 'Bireactiva'),
  ('CA_CPC', 'RISK_SENSIBLE_A_CALIDAD', 'riesgo_operativo', 0.9, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 69', 'Archivo usuario/pendiente IFU', 'Sensible a calidad del agua'),
  ('CER', 'WL_340', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 70', 'Aspects/pages + revisión pendiente', 'Ceruloplasmin usa filtro principal 340 nm'),
  ('CER', 'WL_670', 'usa_filtro_referencia', 0.75, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 71', 'Aspects/pages + revisión pendiente', 'Ceruloplasmin usa filtro referencia 670 nm'),
  ('CER', 'METHOD_DIFERENCIAL_BIREACTIVA', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 72', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Diferencial bireactiva'),
  ('CER', 'RXTYPE_BIREACTIVA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 73', 'Aspects/pages + revisión pendiente', 'Bireactiva'),
  ('CER', 'RISK_CALIBRACION_NO_LIN', 'riesgo_operativo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 74', 'Archivo usuario/pendiente IFU', 'Calibración no lineal/multipunto'),
  ('CHOL', 'WL_505', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 75', 'Aspects/pages + revisión pendiente', 'Cholesterol usa filtro principal 505 nm'),
  ('CHOL', 'WL_670', 'usa_filtro_referencia', 0.75, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 76', 'Aspects/pages + revisión pendiente', 'Cholesterol usa filtro referencia 670 nm'),
  ('CHOL', 'METHOD_PUNTO_FINAL_MONOREACTIVO', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 77', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Punto final monoreactivo'),
  ('CHOL', 'RXTYPE_MONOREACTIVA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 78', 'Aspects/pages + revisión pendiente', 'Monoreactiva'),
  ('CK', 'WL_340', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 79', 'Aspects/pages + revisión pendiente', 'Creatine Kinase CK usa filtro principal 340 nm'),
  ('CK', 'METHOD_CINETICA_BIREACTIVA', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 80', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Cinética bireactiva'),
  ('CK', 'RXTYPE_BIREACTIVA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 81', 'Aspects/pages + revisión pendiente', 'Bireactiva'),
  ('CK', 'RISK_ENZIMATICO_CINETIC', 'riesgo_operativo', 0.75, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 82', 'Archivo usuario/pendiente IFU', 'Enzimático/cinético; grupo 340 nm'),
  ('CREA_ENZ', 'WL_535', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 83', 'Aspects/pages + revisión pendiente', 'Creatinine Enzymatic usa filtro principal 535 nm'),
  ('CREA_ENZ', 'METHOD_DIFERENCIAL_BIREACTIVA', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 84', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Diferencial bireactiva'),
  ('CREA_ENZ', 'RXTYPE_BIREACTIVA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 85', 'Aspects/pages + revisión pendiente', 'Bireactiva'),
  ('CREA_JAFFE', 'WL_535', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 86', 'Aspects/pages + revisión pendiente', 'Creatinine Jaffe usa filtro principal 535 nm'),
  ('CREA_JAFFE', 'METHOD_DIFERENCIAL_BIREACTIVA', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 87', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Diferencial bireactiva'),
  ('CREA_JAFFE', 'RXTYPE_BIREACTIVA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 88', 'Aspects/pages + revisión pendiente', 'Bireactiva'),
  ('FRUCT', 'WL_535', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 89', 'Aspects/pages + revisión pendiente', 'Fructosamine usa filtro principal 535 nm'),
  ('FRUCT', 'METHOD_TIEMPO_FIJO_MONOREACTIVO', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 90', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Tiempo fijo monoreactivo'),
  ('FRUCT', 'RXTYPE_MONOREACTIVA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 91', 'Aspects/pages + revisión pendiente', 'Monoreactiva'),
  ('GGT', 'WL_405', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 92', 'Aspects/pages + revisión pendiente', 'GGT usa filtro principal 405 nm'),
  ('GGT', 'METHOD_CINETICA_BIREACTIVA', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 93', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Cinética bireactiva'),
  ('GGT', 'RXTYPE_BIREACTIVA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 94', 'Aspects/pages + revisión pendiente', 'Bireactiva'),
  ('GGT', 'RISK_ENZIMATICO_CINETIC', 'riesgo_operativo', 0.75, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 95', 'Archivo usuario/pendiente IFU', 'Enzimático/cinético'),
  ('GLU', 'WL_505', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 96', 'Aspects/pages + revisión pendiente', 'Glucose usa filtro principal 505 nm'),
  ('GLU', 'WL_670', 'usa_filtro_referencia', 0.75, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 97', 'Aspects/pages + revisión pendiente', 'Glucose usa filtro referencia 670 nm'),
  ('GLU', 'METHOD_PUNTO_FINAL_MONOREACTIVO', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 98', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Punto final monoreactivo'),
  ('GLU', 'RXTYPE_MONOREACTIVA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 99', 'Aspects/pages + revisión pendiente', 'Monoreactiva'),
  ('G6PDH', 'WL_340', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 100', 'Aspects/pages + revisión pendiente', 'G6PDH usa filtro principal 340 nm'),
  ('G6PDH', 'METHOD_CINETICA_BIREACTIVA', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 101', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Cinética bireactiva'),
  ('G6PDH', 'RXTYPE_BIREACTIVA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 102', 'Aspects/pages + revisión pendiente', 'Bireactiva'),
  ('G6PDH', 'RISK_ENZIMATICO_CINETIC', 'riesgo_operativo', 0.75, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 103', 'Archivo usuario/pendiente IFU', 'Enzimático/cinético; grupo 340 nm'),
  ('GLU_HK', 'WL_340', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 104', 'Aspects/pages + revisión pendiente', 'Glucose-Hexokinase usa filtro principal 340 nm'),
  ('GLU_HK', 'METHOD_DIFERENCIAL_BIREACTIVA', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 105', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Diferencial bireactiva'),
  ('GLU_HK', 'RXTYPE_BIREACTIVA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 106', 'Aspects/pages + revisión pendiente', 'Bireactiva'),
  ('HAPTO', 'WL_340', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 107', 'Aspects/pages + revisión pendiente', 'Haptoglobin usa filtro principal 340 nm'),
  ('HAPTO', 'WL_670', 'usa_filtro_referencia', 0.75, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 108', 'Aspects/pages + revisión pendiente', 'Haptoglobin usa filtro referencia 670 nm'),
  ('HAPTO', 'METHOD_DIFERENCIAL_BIREACTIVA', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 109', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Diferencial bireactiva'),
  ('HAPTO', 'RXTYPE_BIREACTIVA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 110', 'Aspects/pages + revisión pendiente', 'Bireactiva'),
  ('HAPTO', 'RISK_CALIBRACION_NO_LIN', 'riesgo_operativo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 111', 'Archivo usuario/pendiente IFU', 'Calibración no lineal/multipunto'),
  ('HCY', 'WL_340', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 112', 'Aspects/pages + revisión pendiente', 'Homocysteine usa filtro principal 340 nm'),
  ('HCY', 'METHOD_PUNTO_FINAL_BIREACTIVO', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 113', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Punto final bireactivo'),
  ('HCY', 'RXTYPE_BIREACTIVA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 114', 'Aspects/pages + revisión pendiente', 'Bireactiva'),
  ('HCY', 'RISK_CALIBRACION_NO_LIN', 'riesgo_operativo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 115', 'Archivo usuario/pendiente IFU', 'Calibración no lineal/multipunto'),
  ('MG', 'WL_505', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 116', 'Aspects/pages + revisión pendiente', 'Magnesium usa filtro principal 505 nm'),
  ('MG', 'METHOD_PUNTO_FINAL_BIREACTIVO', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 117', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Punto final bireactivo'),
  ('MG', 'RXTYPE_BIREACTIVA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 118', 'Aspects/pages + revisión pendiente', 'Bireactiva'),
  ('MG', 'RISK_SENSIBLE_A_CALIDAD', 'riesgo_operativo', 0.9, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 119', 'Archivo usuario/pendiente IFU', 'Sensible a calidad del agua'),
  ('OX', 'WL_600', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 120', 'Aspects/pages + revisión pendiente', 'Oxalate usa filtro principal 600 nm'),
  ('OX', 'METHOD_DIFERENCIAL_BIREACTIVA', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 121', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Diferencial bireactiva'),
  ('OX', 'RXTYPE_BIREACTIVA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 122', 'Aspects/pages + revisión pendiente', 'Bireactiva'),
  ('OX', 'RISK_MUESTRA_PREANALITI', 'riesgo_operativo', 0.9, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 123', 'Archivo usuario/pendiente IFU', 'Muestra crítica: pH/HCl/estabilidad'),
  ('PHOS', 'WL_340', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 124', 'Aspects/pages + revisión pendiente', 'Phosphorous usa filtro principal 340 nm'),
  ('PHOS', 'METHOD_DIFERENCIAL_BIREACTIVA', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 125', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Diferencial bireactiva'),
  ('PHOS', 'RXTYPE_BIREACTIVA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 126', 'Aspects/pages + revisión pendiente', 'Bireactiva'),
  ('PHOS', 'RISK_SENSIBLE_A_CALIDAD', 'riesgo_operativo', 0.9, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 127', 'Archivo usuario/pendiente IFU', 'Sensible a calidad del agua'),
  ('PROT_U', 'WL_600', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 128', 'Aspects/pages + revisión pendiente', 'Protein Urine usa filtro principal 600 nm'),
  ('PROT_U', 'WL_670', 'usa_filtro_referencia', 0.75, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 129', 'Aspects/pages + revisión pendiente', 'Protein Urine usa filtro referencia 670 nm'),
  ('PROT_U', 'METHOD_PUNTO_FINAL_MONOREACTIVO', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 130', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Punto final monoreactivo'),
  ('PROT_U', 'RXTYPE_MONOREACTIVA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 131', 'Aspects/pages + revisión pendiente', 'Monoreactiva'),
  ('TG', 'WL_505', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 132', 'Aspects/pages + revisión pendiente', 'Triglycerides usa filtro principal 505 nm'),
  ('TG', 'WL_670', 'usa_filtro_referencia', 0.75, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 133', 'Aspects/pages + revisión pendiente', 'Triglycerides usa filtro referencia 670 nm'),
  ('TG', 'METHOD_PUNTO_FINAL_MONOREACTIVO', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 134', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Punto final monoreactivo'),
  ('TG', 'RXTYPE_MONOREACTIVA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 135', 'Aspects/pages + revisión pendiente', 'Monoreactiva'),
  ('TBA', 'WL_405', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 136', 'Aspects/pages + revisión pendiente', 'Total Bile Acids usa filtro principal 405 nm'),
  ('TBA', 'METHOD_TIEMPO_FIJO_BIREACTIVO', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 137', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Tiempo fijo bireactivo'),
  ('TBA', 'RXTYPE_BIREACTIVA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 138', 'Aspects/pages + revisión pendiente', 'Bireactiva'),
  ('UREA_COLOR', 'WL_600', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 139', 'Aspects/pages + revisión pendiente', 'Urea BUN-Color usa filtro principal 600 nm'),
  ('UREA_COLOR', 'METHOD_PUNTO_FINAL_BIREACTIVO', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 140', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Punto final bireactivo'),
  ('UREA_COLOR', 'RXTYPE_BIREACTIVA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 141', 'Aspects/pages + revisión pendiente', 'Bireactiva'),
  ('UREA_UV', 'WL_340', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 142', 'Aspects/pages + revisión pendiente', 'Urea BUN-UV usa filtro principal 340 nm'),
  ('UREA_UV', 'METHOD_TIEMPO_FIJO_MONOREACTIVO', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 143', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Tiempo fijo monoreactivo'),
  ('UREA_UV', 'METHOD_TIEMPO_FIJO_BIREACTIVO', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 144', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Tiempo fijo bireactivo'),
  ('UREA_UV', 'RXTYPE_VARIABLE_POR_PLATAFORMA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 145', 'Aspects/pages + revisión pendiente', 'Variable por plataforma'),
  ('UREA_UV', 'RISK_CAMBIO_POR_LOTE_PL', 'riesgo_operativo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 146', 'Archivo usuario/pendiente IFU', 'Cambia según plataforma'),
  ('URIC', 'WL_505', 'usa_filtro_principal', 1, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 147', 'Aspects/pages + revisión pendiente', 'Uric Acid usa filtro principal 505 nm'),
  ('URIC', 'WL_670', 'usa_filtro_referencia', 0.75, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 148', 'Aspects/pages + revisión pendiente', 'Uric Acid usa filtro referencia 670 nm'),
  ('URIC', 'METHOD_PUNTO_FINAL_MONOREACTIVO', 'comparte_metodo', 0.85, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 149', 'Aspects/pages + revisión pendiente', 'Método reportado incluye: Punto final monoreactivo'),
  ('URIC', 'RXTYPE_MONOREACTIVA', 'tipo_reaccion', 0.8, 'pending', 'manual', 'Workbook DRI · DRI_tablas_revision_reactivos_biosystems.xlsx · 03_Relaciones_Grafo · fila 150', 'Aspects/pages + revisión pendiente', 'Monoreactiva')
on conflict (reagent_id, factor_id, relation_type) do update
set
  weight = excluded.weight,
  confidence = excluded.confidence,
  source_type = excluded.source_type,
  source_reference = excluded.source_reference,
  source_label = excluded.source_label,
  note = excluded.note,
  updated_at = timezone('utc', now());

commit;
